# Default values for rust.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: "pfeiffermax/windrose-dedicated-server"
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # Please see Docker Hub for available tags: https://hub.docker.com/r/pfeiffermax/rust-game-server/tags
  tag: "latest"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault


securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
headlessService:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  metadata:
    annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Windrose dedicated server startup is slow, so you might need to bump up periodSeconds and failureThreshold
# if you see the startup probe failing.
startupProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 100
  successThreshold: 1

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

windroseDedicatedServer:
  # Port for the Windrose Services.
  port: 28050
  # Size of the volume the server uses for its saves directory.
  volumeStorageSize: "1Gi"
  # Name of the existing secret to use for the server password.
  # If this is set, windroseDedicatedServer.password will be ignored.
  # The existing secret needs to have stored Windrose server password under the key password.
  existingSecret: ""

# You can choose to run multiple instances of Rust dedicated servers here.
# For a new instance add another entry to this list.
instances:
    # Name of your server. Helpful if invite codes look similar
  - name: "WindroseServer"
    # Server password
    password: "supersecret"
    # Invite code to find your server. 0-9, a-z and A-Z symbols are allowed. Should contain at least 6 symbols.
    # Case sensitive.
    inviteCode: ""
    # Maximum number of simultaneous players on your server.
    maxPlayerCount: "5"
    # Specifies the region for the Connection Service. Supported options: SEA, CIS, EU (EU covers both EU & NA).
    # If left empty, the server will automatically detect and select the optimal region based on latency. If desired
    # region is specified (for example, EU), the server will use that region exclusively.
    userSelectedRegion: ""
    # IP Address for listening sockets.
    p2pProxyAddress: ""
    # If true, the server will create sockets for direct connection with clients. If false, the server will use ICE
    # protocol to establish P2P connection.
    useDirectConnection: "true"
    # Address for direct connection. For future purposes. Not used now.
    directConnectionServerAddress: ""
    # Port for direct connection. Should be available for TCP and UDP connection if UseDirectConnection is true.
    directConnectionServerPort: "28050"
    # Can be used to choose specified network on computer where server with direct connection is running.
    # 0.0.0.0 should be used by default.
    directConnectionProxyAddress: "0.0.0.0"
    # Service configuration for this instance
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      metadata:
        labels: {}
        annotations: {}
