apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "windrose.fullname" . }}
  labels:
    {{- include "windrose.labels" . | nindent 4 }}
data:
  {{- range $i, $instance := .Values.instances }}
  {{ include "windrose.fullname" $ }}-{{ $i }}: |
    SERVER_NAME={{ $instance.name }}
    INVITE_CODE={{ $instance.inviteCode }}
    MAX_PLAYER_COUNT={{ $instance.maxPlayerCount }}
    USER_SELECTED_REGION={{ $instance.userSelectedRegion }}
    USE_DIRECT_CONNECTION=true
    DIRECT_CONNECTION_SERVER_PORT={{ $.Values.windroseDedicatedServer.port }}
    DIRECT_CONNECTION_PROXY_ADDRESS=0.0.0.0
  {{- end }}