{{- if not .Values.windroseDedicatedServer.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "windrose.fullname" . }}
  labels:
    {{- include "windrose.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $i, $instance := .Values.instances }}
  {{ include "windrose.fullname" $ }}-{{ $i }}: |
    password="{{ $instance.password }}"
  {{- end }}
{{- end }}