apiVersion: v1
kind: Service
metadata:
  name: {{ include "windrose.fullname" . }}
  labels:
    {{- include "windrose.labels" . | nindent 4 }}
  {{- with .Values.headlessService.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.headlessService.type }}
  clusterIP: None
  ports:
    - name: server-port-tcp
      port: {{ .Values.windroseDedicatedServer.port }}
      targetPort: server-port-tcp
      protocol: TCP
    - name: server-port-udp
      port: {{ .Values.windroseDedicatedServer.port }}
      targetPort: server-port-udp
      protocol: UDP
  selector:
    {{- include "windrose.selectorLabels" . | nindent 4 }}
---
{{- range $i, $instance := .Values.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "windrose.fullname" $ }}-{{ $i }}
  labels:
    {{- include "windrose.labels" $ | nindent 4 }}
    {{- with $instance.service.metadata.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $instance.service.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $instance.service.type }}
  externalTrafficPolicy: {{ $instance.service.externalTrafficPolicy }}
  ports:
    - name: server-port-tcp
      port: {{ .Values.windroseDedicatedServer.port }}
      targetPort: server-port-tcp
      protocol: TCP
    - name: server-port-udp
      port: {{ .Values.windroseDedicatedServer.port }}
      targetPort: server-port-udp
      protocol: UDP
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "windrose.fullname" $ }}-{{ $i }}
---
{{- end }}