name: valheim

services:
  init-container:
    image: alpine:3.23
    container_name: "init-container"
    user: root
    command:
      - "/bin/sh"
      - "-c"
      - "chown -R 10001:10001 /srv/windrose/R5/Saved"
    volumes:
      - type: volume
        source: save_dir
        target: "/srv/windrose/R5/Saved"
  windrose-server:
    image: "pfeiffermax/windrose-dedicated-server:latest"
    pull_policy: never
    container_name: "windrose-server"
    environment:
      PASSWORD: "supersecret"
      SERVER_NAME: "Atlantis"
      MAX_PLAYER_COUNT: "5"
      USER_SELECTED_REGION: "EU"
      USE_DIRECT_CONNECTION: "true"
      DIRECT_CONNECTION_SERVER_PORT: "28050"
    ports:
      - "28050:28050/tcp"
      - "28050:28050/udp"
    volumes:
      - type: volume
        source: save_dir
        target: "/srv/windrose/R5/Saved"

volumes:
  save_dir:
    name: "windrose-save-dir"
