name: Test Image Build

on:
  pull_request:
    paths:
      - .github/**
      - build/**
      - tests/**
      - poetry.lock

jobs:
  test-image-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root
      - name: Run tests with pytest
        run: |
          poetry run pytest --cov build --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}